---
- hosts: postgresql
  become: yes

  pre_tasks:
    - name: Uninstall urllib3 2
      ansible.builtin.pip:
        name: urllib3
        version: 2.0
        state: absent

    - name: Install urllib3 1
      ansible.builtin.pip:
        name: urllib3
        version: 1.26
        state: forcereinstall
        #forcereinstall: true

    - name: Install docker-py python package
      ansible.builtin.pip:
        name: docker-py
        state: present

    - name: Install Docker Engine
      ansible.builtin.yum:
        name:
          - docker
        state: present


    #usermod -a -G docker ec2-user
    - name: Add the user 'ec2-user' to docker
      ansible.builtin.user:
        name: ec2-user
        groups: docker
  tasks:

    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - docker

    - name: "Template SQL init script"
      ansible.builtin.template:
         src: files/init.sql.j2
         dest: /tmp/init.sql

    - name: Create a network
      docker_network:
        name: network_one

    - name: Ensure the postgresql container is here
      community.docker.docker_container:
        name: heroes-db
        image: postgres:14
        ports:
        - "5432:5432"
        env:
          POSTGRES_USER: "{{ POSTGRES_USER }}"
          POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
          POSTGRES_DB: "{{ POSTGRES_DB }}"
        volumes:
          - /tmp/init.sql:/docker-entrypoint-initdb.d/1-init-tables.sql
        networks:
          - name: "network_one"
    