---
- hosts: rest-heroes-api
  become: yes

  pre_tasks:
    - name: Uninstall urllib3 2
      ansible.builtin.pip:
        name: urllib3
        version: 2.0
        state: absent

    - name: Install urllib3 1
      ansible.builtin.pip:
        name: urllib3
        version: 1.26
        state: forcereinstall
        #forcereinstall: true

    - name: Install requests python package
      ansible.builtin.pip:
        name: docker-py
        state: present

    - name: Install Docker Engine
      ansible.builtin.yum:
        name:
          - docker
        state: present

  tasks:
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - docker

    - name: "Initialize database"
      ansible.builtin.shell:
        #become: true
        #become_user: docker
        args: docker login
        # -u {{ REGISTRY_USERNAME }} -p {{ REGISTRY_PASSWORD }} {{ REGISTRY_URL }}