---
- hosts: rest-heroes-api
  become: yes

  pre_tasks:
    - name: Install Docker Engine
      ansible.builtin.yum:
        name:
          - # A completer
        state: present

  tasks: 
    - name: "Start and enable services"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - # A completer